import type { ThemeConfig } from 'antd';

export const themeConfig: ThemeConfig = {
  token: {
    colorPrimary: '#3157D5',
    colorInfo: '#3157D5',
    colorLink: '#3157D5',
    colorSuccess: '#158A6A',
    colorWarning: '#C58B22',
    colorError: '#C2414B',
    borderRadius: 9,
    colorBgContainer: '#ffffff',
    colorBgLayout: '#f5f7fb',
    colorText: '#0f172a',
    colorTextSecondary: '#667085',
    colorBorder: '#e6ebf2',
    colorBorderSecondary: '#eef2f7',
    fontSize: 11.5,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Inter", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    lineHeight: 1.68,
    boxShadowSecondary: '0 1px 2px rgba(15, 23, 42, 0.03), 0 12px 30px rgba(15, 23, 42, 0.04)',
    boxShadowTertiary: '0 1px 2px rgba(15, 23, 42, 0.03), 0 20px 48px rgba(15, 23, 42, 0.06)',
    controlOutline: 'rgba(49, 87, 213, 0.12)',
    controlOutlineWidth: 4,
  },
  components: {
    Card: {
      colorBorderSecondary: 'transparent',
      bodyPadding: 15,
      headerPadding: 15,
      borderRadiusLG: 17,
      boxShadowTertiary: '0 1px 2px rgba(15, 23, 42, 0.03), 0 14px 36px rgba(15, 23, 42, 0.05)',
    },
    Table: {
      headerBg: '#f8faff',
      headerColor: '#0f172a',
      borderColor: '#edf1f7',
      cellPaddingBlock: 11,
      cellPaddingInline: 11,
      rowHoverBg: '#f8faff',
      headerSplitColor: 'transparent',
    },
    Menu: {
      colorSplit: 'transparent',
      itemBorderRadius: 12,
      itemMarginInline: 8,
      itemMarginBlock: 6,
      itemSelectedBg: '#edf3ff',
      itemSelectedColor: '#0f172a',
      itemHoverColor: '#0f172a',
      itemHoverBg: '#f8faff',
      subMenuItemBg: 'transparent',
      groupTitleColor: '#94a3b8',
    },
    Layout: {
      bodyBg: '#f5f7fb',
      siderBg: '#ffffff',
      headerBg: '#ffffff',
    },
    Button: {
      fontWeight: 600,
      controlHeight: 38,
      borderRadius: 9,
      primaryShadow: '0 10px 24px rgba(49, 87, 213, 0.16)',
    },
    Input: {
      borderRadius: 9,
      activeBorderColor: '#3157D5',
      hoverBorderColor: '#3157D5',
    },
    InputNumber: {
      borderRadius: 9,
      activeBorderColor: '#3157D5',
      hoverBorderColor: '#3157D5',
    },
    Select: {
      borderRadius: 9,
      activeBorderColor: '#3157D5',
      hoverBorderColor: '#3157D5',
      optionSelectedBg: '#edf3ff',
    },
    DatePicker: {
      borderRadius: 9,
      activeBorderColor: '#3157D5',
      hoverBorderColor: '#3157D5',
    },
    Form: {
      itemMarginBottom: 13,
    },
    Tabs: {
      inkBarColor: '#3157D5',
      itemSelectedColor: '#0f172a',
      itemHoverColor: '#3157D5',
      itemColor: '#64748b',
    },
    Drawer: {
      colorBgElevated: '#ffffff',
    },
    Modal: {
      contentBg: '#ffffff',
      headerBg: '#ffffff',
      titleColor: '#0f172a',
    },
    Tag: {
      defaultBg: '#f8faff',
      defaultColor: '#475569',
    },
  },
};
